# Generated by Django 5.2.1 on 2025-06-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_company_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='description',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='education',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(default='1', upload_to='resumes/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='skills',
            field=models.ManyToManyField(related_name='skills', to='clients.skill'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='years_of_experience',
            field=models.PositiveIntegerField(default='1'),
            preserve_default=False,
        ),
    ]
