# Generated by Django 5.2.1 on 2025-07-01 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_candidate_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('appliers_count', models.PositiveSmallIntegerField()),
                ('employer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='clients.companyemployee')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='clients.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliers', to='clients.job')),
            ],
        ),
    ]
