# Generated by Django 5.2.1 on 2025-06-13 17:26

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_agencyemployeeuser_alter_agencyemployee_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateUser',
            fields=[
            ],
            options={
                'verbose_name': 'Candidate User',
                'verbose_name_plural': 'Candidate Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
