# Generated by Django 5.2.1 on 2025-06-13 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_candidateuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='agencyemployee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.position'),
        ),
    ]
