# Generated by Django 5.2.1 on 2025-06-16 19:25

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_position_alter_agencyemployee_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEmployeeUser',
            fields=[
            ],
            options={
                'verbose_name': 'Candidate User',
                'verbose_name_plural': 'Company Employee Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
