# Generated by Django 5.2.1 on 2025-06-02 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_message_read_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read_by',
        ),
    ]
